[functions]
included_files = [
  "./static/*",
  "./src/utils/*",
  "./node_modules/@fontsource/press-start-2p/files/press-start-2p-latin-400-normal.woff",
  "./node_modules/@fontsource/raleway/files/raleway-latin-200-normal.woff",
]

[functions."scheduled"]
# schedule = "*/5 * * * *" # every 5 minutes
schedule = "0 */8 * * *" # every 8 hours
