[functions]
included_files = [
  "./static/*",
  "./src/utils/*",
  "./node_modules/orgdot-org-v01/Orgv01.woff",
  "./node_modules/typeface-raleway/files/raleway-latin-200.woff",
]

# [functions."twitter"]
# schedule = "0 */8 * * *"
