# name: Gatsby Publish

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: enriikke/gatsby-gh-pages-action@v2
#         with:
#           access-token: ${{ secrets.ACCESS_TOKEN }}
#           deploy-branch: gh-pages
#           gatsby-args: --prefix-paths
#         env:
#           CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
#           CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
#           CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
